# Generated by Django 5.1.7 on 2025-04-14 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelancer', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'work_request_status',
            },
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('id_freelancer', models.ForeignKey(db_column='id_freelancer', on_delete=django.db.models.deletion.DO_NOTHING, to='freelancer.freelancer')),
                ('id_project', models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.DO_NOTHING, to='project.project')),
                ('id_status', models.ForeignKey(db_column='id_status', on_delete=django.db.models.deletion.DO_NOTHING, to='workrequest.workrequeststatus')),
            ],
            options={
                'db_table': 'work_request',
            },
        ),
    ]
