# Generated by Django 5.1.7 on 2025-05-15 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
        ('project', '0001_initial'),
        ('workrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='id_freelancer',
            field=models.ForeignKey(blank=True, db_column='id_freelancer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='freelancer.freelancer'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='id_project',
            field=models.ForeignKey(blank=True, db_column='id_project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
    ]
