# Generated by Django 5.1.7 on 2025-04-14 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('id_appraiser', models.ForeignKey(db_column='id_appraiser', on_delete=django.db.models.deletion.CASCADE, related_name='rating_id_appraiser_set', to=settings.AUTH_USER_MODEL)),
                ('id_evaluates', models.ForeignKey(db_column='id_evaluates', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('id_project', models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.DO_NOTHING, to='project.project')),
            ],
            options={
                'db_table': 'rating',
            },
        ),
    ]
